config/routes.rb
Rails.application.routes.draw do
  resources :advertisements
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/advertisement.rb
class Advertisement
  include Mongoid::Document
  include Mongoid::Attributes::Dynamic
  field :start_datetime, type: Time
  field :end_datetime, type: Time
  field :image_url, type: String
  field :advertisement_id, type: Integer
  field :advertisement_name, type: String
  field :campaign_id, type: Integer
  field :campaign_name, type: String
  field :campaign_customers_name, type: String
  field :screen_id, type: Integer
  field :template_id, type: Integer
  field :grid_id, type: Integer
  field :position, type: Float
  field :widget_size, type: String
end

app/controllers/advertisements_controller.rb
class AdvertisementsController < ApplicationController
  before_action :set_advertisement, only: [:show, :edit, :update, :destroy]

  # GET /advertisements
  # GET /advertisements.json
  def index
    @advertisements = Advertisement.all
  end

  # GET /advertisements/1
  # GET /advertisements/1.json
  def show
  end

  # GET /advertisements/new
  def new
    @advertisement = Advertisement.new
  end

  # GET /advertisements/1/edit
  def edit
  end

  # POST /advertisements
  # POST /advertisements.json
  def create
    @advertisement = Advertisement.new(advertisement_params)

    respond_to do |format|
      if @advertisement.save
        format.html { redirect_to @advertisement, notice: 'Advertisement was successfully created.' }
        format.json { render :show, status: :created, location: @advertisement }
      else
        format.html { render :new }
        format.json { render json: @advertisement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /advertisements/1
  # PATCH/PUT /advertisements/1.json
  def update
    respond_to do |format|
      if @advertisement.update(advertisement_params)
        format.html { redirect_to @advertisement, notice: 'Advertisement was successfully updated.' }
        format.json { render :show, status: :ok, location: @advertisement }
      else
        format.html { render :edit }
        format.json { render json: @advertisement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /advertisements/1
  # DELETE /advertisements/1.json
  def destroy
    @advertisement.destroy
    respond_to do |format|
      format.html { redirect_to advertisements_url, notice: 'Advertisement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_advertisement
      @advertisement = Advertisement.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def advertisement_params
      params.require(:advertisement).permit(:start_datetime, :end_datetime, :image_url, :advertisement_id, :advertisement_name, :campaign_id, :campaign_name, :campaign_customers_name, :screen_id, :template_id, :grid_id, :position, :widget_size)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/advertisements_helper.rb
module AdvertisementsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/advertisements/_form.html.erb
<%= form_with(model: advertisement, local: true) do |form| %>
  <% if advertisement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(advertisement.errors.count, "error") %> prohibited this advertisement from being saved:</h2>

      <ul>
        <% advertisement.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :start_datetime %>
    <%= form.datetime_select :start_datetime %>
  </div>

  <div class="field">
    <%= form.label :end_datetime %>
    <%= form.datetime_select :end_datetime %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url %>
  </div>

  <div class="field">
    <%= form.label :advertisement_id %>
    <%= form.number_field :advertisement_id %>
  </div>

  <div class="field">
    <%= form.label :advertisement_name %>
    <%= form.text_field :advertisement_name %>
  </div>

  <div class="field">
    <%= form.label :campaign_id %>
    <%= form.number_field :campaign_id %>
  </div>

  <div class="field">
    <%= form.label :campaign_name %>
    <%= form.text_field :campaign_name %>
  </div>

  <div class="field">
    <%= form.label :campaign_customers_name %>
    <%= form.text_field :campaign_customers_name %>
  </div>

  <div class="field">
    <%= form.label :screen_id %>
    <%= form.number_field :screen_id %>
  </div>

  <div class="field">
    <%= form.label :template_id %>
    <%= form.number_field :template_id %>
  </div>

  <div class="field">
    <%= form.label :grid_id %>
    <%= form.number_field :grid_id %>
  </div>

  <div class="field">
    <%= form.label :position %>
    <%= form.text_field :position %>
  </div>

  <div class="field">
    <%= form.label :widget_size %>
    <%= form.text_field :widget_size %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/advertisements/edit.html.erb
<h1>Editing Advertisement</h1>

<%= render 'form', advertisement: @advertisement %>

<%= link_to 'Show', @advertisement %> |
<%= link_to 'Back', advertisements_path %>

app/views/advertisements/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Advertisements</h1>

<table>
  <thead>
    <tr>
      <th>Start datetime</th>
      <th>End datetime</th>
      <th>Image url</th>
      <th>Advertisement</th>
      <th>Advertisement name</th>
      <th>Campaign</th>
      <th>Campaign name</th>
      <th>Campaign customers name</th>
      <th>Screen</th>
      <th>Template</th>
      <th>Grid</th>
      <th>Position</th>
      <th>Widget size</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @advertisements.each do |advertisement| %>
      <tr>
        <td><%= advertisement.start_datetime %></td>
        <td><%= advertisement.end_datetime %></td>
        <td><%= advertisement.image_url %></td>
        <td><%= advertisement.advertisement_id %></td>
        <td><%= advertisement.advertisement_name %></td>
        <td><%= advertisement.campaign_id %></td>
        <td><%= advertisement.campaign_name %></td>
        <td><%= advertisement.campaign_customers_name %></td>
        <td><%= advertisement.screen_id %></td>
        <td><%= advertisement.template_id %></td>
        <td><%= advertisement.grid_id %></td>
        <td><%= advertisement.position %></td>
        <td><%= advertisement.widget_size %></td>
        <td><%= link_to 'Show', advertisement %></td>
        <td><%= link_to 'Edit', edit_advertisement_path(advertisement) %></td>
        <td><%= link_to 'Destroy', advertisement, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Advertisement', new_advertisement_path %>

app/views/advertisements/new.html.erb
<h1>New Advertisement</h1>

<%= render 'form', advertisement: @advertisement %>

<%= link_to 'Back', advertisements_path %>

app/views/advertisements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Start datetime:</strong>
  <%= @advertisement.start_datetime %>
</p>

<p>
  <strong>End datetime:</strong>
  <%= @advertisement.end_datetime %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @advertisement.image_url %>
</p>

<p>
  <strong>Advertisement:</strong>
  <%= @advertisement.advertisement_id %>
</p>

<p>
  <strong>Advertisement name:</strong>
  <%= @advertisement.advertisement_name %>
</p>

<p>
  <strong>Campaign:</strong>
  <%= @advertisement.campaign_id %>
</p>

<p>
  <strong>Campaign name:</strong>
  <%= @advertisement.campaign_name %>
</p>

<p>
  <strong>Campaign customers name:</strong>
  <%= @advertisement.campaign_customers_name %>
</p>

<p>
  <strong>Screen:</strong>
  <%= @advertisement.screen_id %>
</p>

<p>
  <strong>Template:</strong>
  <%= @advertisement.template_id %>
</p>

<p>
  <strong>Grid:</strong>
  <%= @advertisement.grid_id %>
</p>

<p>
  <strong>Position:</strong>
  <%= @advertisement.position %>
</p>

<p>
  <strong>Widget size:</strong>
  <%= @advertisement.widget_size %>
</p>

<%= link_to 'Edit', edit_advertisement_path(@advertisement) %> |
<%= link_to 'Back', advertisements_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YoushowAnalytics</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>